#!/usr/bin/env bash
# Optional: campus WPA2-Enterprise wifi on wlo1, as a fallback path.
#   sudo ~/homelab/scripts/magi/30-wifi.sh [SSID]
#
# Wired stays preferred — route-metric 600 here against 100 for ethernet — so this
# only carries traffic when the cable is out. Its point is that MAGI keeps a way
# onto the tailnet if the adapter dies or its USB-C port is needed for something else.
#
# CREDENTIALS: prompted for, never echoed, and written straight into a root-only
# netplan file. They are NOT committed, NOT logged, and NOT recoverable from the
# repo — if you rebuild MAGI, you type them again. That is the intended trade:
# rule 1 says a secret never enters the repo, and a wifi password you can retype
# is not worth weakening that for.
set -euo pipefail
[[ $EUID -eq 0 ]] || { echo "run with sudo"; exit 1; }

SSID="${1:-IITJ_WLAN}"
IFACE=$(ls /sys/class/net | grep -E '^wl' | head -1)
[[ -n "$IFACE" ]] || { echo "no wireless interface found"; exit 1; }
F=/etc/netplan/30-magi-wifi.yaml

echo "SSID:      $SSID"
echo "interface: $IFACE"
read -rp  "identity (campus username): " ID
read -rsp "password (not shown): " PW; echo
[[ -n "$ID" && -n "$PW" ]] || { echo "both are required"; exit 1; }

# YAML double-quoted scalars take \\ and \" — escape both so a password containing
# either doesn't produce a file that parses as something else.
esc() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

BAK=""
[[ -f "$F" ]] && { BAK=$(mktemp); cp -a "$F" "$BAK"; }

umask 077
cat > "$F" <<EOF
# Generated by scripts/magi/30-wifi.sh — contains credentials, never commit this.
network:
  version: 2
  renderer: networkd
  wifis:
    $IFACE:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 600
      optional: true
      access-points:
        "$(esc "$SSID")":
          auth:
            key-management: eap
            method: peap
            identity: "$(esc "$ID")"
            password: "$(esc "$PW")"
EOF
unset PW
chmod 600 "$F"; chown root:root "$F"

if ! netplan generate 2>&1; then
  echo "netplan rejected the config — reverting"
  rm -f "$F"; [[ -n "$BAK" ]] && cp -a "$BAK" "$F"
  netplan generate; exit 1
fi

rfkill unblock wifi 2>/dev/null || true
netplan apply

echo -n "associating"
for _ in $(seq 45); do
  IP=$(ip -4 -br addr show "$IFACE" 2>/dev/null | awk '{print $3}')
  [[ -n "$IP" ]] && break
  echo -n "."; sleep 1
done
echo

if [[ -n "${IP:-}" ]]; then
  echo "OK: $IFACE has $IP"
  ip route | grep "$IFACE" || true
  echo "wired stays preferred; pull the ethernet cable to actually test this path."
else
  echo "FAILED to get an address on $IFACE."
  echo "Most likely the EAP method isn't PEAP/MSCHAPv2. Check with:"
  echo "  journalctl -u wpa_supplicant -n 40 --no-pager"
  echo "Leaving the config in place — it is 'optional', so it cannot block boot."
  echo "Remove it with: rm $F && netplan apply"
fi
[[ -n "$BAK" ]] && shred -u "$BAK" 2>/dev/null || true
