#!/usr/bin/env bash
# Authelia — SSO in front of everything H-04 adds.
#
# Stood up before the services it protects, on purpose: retrofitting
# forward-auth across eight running services means editing eight Caddyfile
# blocks and re-testing eight login flows.
#
# Idempotent. Re-run it to apply a config change; pass --reset-user to set a
# new password, or --reset-secrets to roll the three keys (which invalidates
# every session and every stored TOTP registration).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STACK="$REPO/compose/authelia/compose.yaml"
ENVF="$REPO/secrets/authelia.env"
USERS="$REPO/secrets/authelia/users.yml"
IMAGE="authelia/authelia:4.39"

install -d -m 700 "$REPO/secrets" "$REPO/secrets/authelia"

rand() { head -c 96 /dev/urandom | base64 | tr -d '\n=+/' | head -c 64; }

if [ ! -f "$ENVF" ] || [ "${1:-}" = --reset-secrets ]; then
  # Empty at 0600 first, then written into — the keys are never on disk at
  # looser permissions and never pass through a temp file. Same shape as
  # 60-observability.sh.
  install -m 600 /dev/null "$ENVF"
  {
    printf 'AUTHELIA_SESSION_SECRET=%s\n' "$(rand)"
    printf 'AUTHELIA_STORAGE_ENCRYPTION_KEY=%s\n' "$(rand)"
    printf 'AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=%s\n' "$(rand)"
  } > "$ENVF"
  echo "wrote $ENVF (3 keys, 64 chars each)"
fi

if [ ! -f "$USERS" ] || [ "${1:-}" = --reset-user ]; then
  read -rp  "Authelia username: " USER_NAME
  read -rp  "Display name: "      DISPLAY_NAME
  read -rp  "Email (any address; only used as a login identifier here): " EMAIL
  read -rsp "Password: " PASS; echo

  # --password puts the password in the container's argv, so it is visible in
  # `ps` for the second the container lives. Authelia's CLI offers no stdin or
  # file input — it demands a TTY otherwise, which cannot be captured. On a
  # single-user box reachable only over the tailnet that is the proportionate
  # trade; the alternative is a pty-capture contraption to close a one-second
  # local window.
  DIGEST="$(docker run --rm -i "$IMAGE" \
    authelia crypto hash generate argon2 --password "$PASS" --no-confirm \
    | tr -d '\r' | sed -n 's/^Digest: //p' | head -1)"
  unset PASS
  [ -n "$DIGEST" ] || { echo "hashing failed" >&2; exit 1; }

  install -m 600 /dev/null "$USERS"
  cat > "$USERS" <<EOF
# Generated by scripts/magi/65-authelia.sh. Gitignored — R2 cannot regenerate
# this one, so it joins the list in CLAUDE.md.
users:
  ${USER_NAME}:
    disabled: false
    displayname: "${DISPLAY_NAME}"
    password: "${DIGEST}"
    email: ${EMAIL}
    groups:
      - admins
EOF
  unset DIGEST
  echo "wrote $USERS (user: $USER_NAME)"
fi

docker compose -f "$STACK" up -d
# Bind mounts don't trigger a recreate, so a changed configuration.yml needs
# this to take effect (same reason as 50-mqtt.sh and 60-observability.sh).
docker compose -f "$STACK" restart authelia
docker compose -f "$REPO/compose/caddy/compose.yaml" restart caddy
echo
docker compose -f "$STACK" ps
